name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore Packages
      run:  nuget restore Screenplay.XUnit.sln
    - name: Build
      run:  msbuild.exe Screenplay.XUnit.sln   
